Frontend View
deepredsky/IconExtractor pull request #1
Opened 2018-07-25 14:11 UTC by nirmalathapa

Add css file and cdn bulma framework for the input field and button with html class.

2018-07-25 19:09 UTC, deepredsky requested changes
the static files need to be in `static` folder

2018-07-26 15:17 UTC, nirmalathapa commented
Fixed static file path

2018-07-30 20:27 UTC, deepredsky commented on index.html
> +    <link rel="stylesheet" href="static/css/style.css">
`static/css/style.css` should be `css/style.css` to run it thru scotty

2018-07-31 19:32 UTC, deepredsky approved these changes

2018-07-31 19:32 UTC, merged